import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)) + "/../../qm_mb_energy_calculator/src")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)) + "/../../")
import molecule_parser
import settings_reader
def generate_configurations(settings_path, geo_path, nm_path, dim_null, config_path):
    """
    Generates a set of 1b configurations for a molecule given its optimized geometry and normal modes.

    Args:
        settings_path - path to the .ini file with relevant settings
        geo_path - path to the optimized geometry .xyz file
        nm_path - path to normal modes file as generated by generate_normal_modes
        dim_null - the null dimension of this molecule, as returned by generate_normal_modes
        config_path - path to the file to write the configurations, existing content will be clobbered.
    """

    print("Running normal distribution configuration generator...")
    
    settings = settings_reader.SettingsReader(settings_path)

    # read the optimized geometry    
    molecule = molecule_parser.xyz_to_molecules(geo_path, settings)[0]

    input_path = settings.get("files", "log_path") + "/config_generator/{}.in".format(molecule.get_name())

    # make sure that the directory in which to write the input_path file exists
    if not os.path.exists(os.path.dirname(input_path)):
        os.makedirs(os.path.dirname(input_path))

    # construct the input file for the Fortran configurations generator code
    with open(input_path, "w") as input_file:
        input_file.write("'" + geo_path + "'\n") # path to optimized geometry
        input_file.write("'" + nm_path + "'\n") # path to normal modes
        input_file.write(str(3 * molecule.get_num_atoms()) + " " + str(dim_null) + "\n") # dim followed by dimnull
        input_file.write(settings.get("config_generator", "random") + " " + settings.get("config_generator", "num_configs") + "\n") # random method followed by number of configs
        input_file.write("'" + config_path + "'\n") # path to output file
        input_file.write(settings.get("config_generator", "geometric") + " " + settings.get("config_generator", "linear") + "\n") # whether to use geometric progression followed by whether to use linear progression
        input_file.write(".true.") # provide verbose output
    
    log_path = settings.get("files", "log_path") + "/config_generator/{}.log".format(molecule.get_name())

    os.system(os.path.dirname(os.path.abspath( __file__ )) + "/../norm_distribution/src/generate_configs_normdistrbn < " + input_path + " > " + log_path)

    print("Normal Distribution Configuration generation complete.")
        
if __name__ == "__main__":
    if len(sys.argv) != 6:
        print("Usage: python geometry_optimizer.py <settings> <geo_path> <normal_modes_path> <dim null> <config_path>")
        exit(1)
    generate_configurations(sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4]), sys.argv[5])
